---
- name: Install otel collector
  ansible.builtin.import_role:
    name: grafana.grafana.opentelemetry_collector
    tasks_from: install

- name: Allow journald access to the otel user
  ansible.builtin.user:
    name: "{{ otel_user }}"
    groups: ["systemd-journal"]
    append: true

- name: Configure otel collector
  ansible.builtin.import_role:
    name: grafana.grafana.opentelemetry_collector
    tasks_from: configure

- name: Setup otel service
  ansible.builtin.import_role:
    name: grafana.grafana.opentelemetry_collector
    tasks_from: service
